// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.vvs.dfa.graphwalker;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "main/resources/testautomation/VVS.graphml")
public interface VVS {

    @Vertex()
    void Ready();

    @Edge()
    void add_state();

}
